# Generated by Django 6.0.1 on 2026-01-19 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeographyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(db_index=True, max_length=6)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'district'], name='dashboard_g_state_c84c72_idx')],
                'unique_together': {('state', 'district', 'pincode')},
            },
        ),
        migrations.CreateModel(
            name='EnrolmentFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('dqs_score', models.FloatField(default=0.0)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(default='Unknown', max_length=20)),
                ('age_band', models.CharField(default='Unknown', max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.geographymaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DemographicFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('dqs_score', models.FloatField(default=0.0)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('age_band', models.CharField(default='Unknown', max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.geographymaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BiometricUpdateFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('dqs_score', models.FloatField(default=0.0)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('update_type', models.CharField(default='General', max_length=50)),
                ('count', models.PositiveIntegerField(default=0)),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.geographymaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
