# Generated by Django 5.2.8 on 2026-01-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricupdatefact',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='biometricupdatefact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='demographicfact',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='demographicfact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enrolmentfact',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='enrolmentfact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='geographymaster',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
