# Generated by Django 6.0.1 on 2026-01-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_biometricupdatefact_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AadharBiometric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('bio_age_5_17', models.IntegerField(default=0)),
                ('bio_age_17_greater', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AadharDemographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('demo_age_5_17', models.IntegerField(default=0)),
                ('demo_age_17_greater', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AadharEnrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('age_0_5', models.IntegerField(default=0)),
                ('age_5_17', models.IntegerField(default=0)),
                ('age_18_greater', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='biometricupdatefact',
            name='geography',
        ),
        migrations.RemoveField(
            model_name='demographicfact',
            name='geography',
        ),
        migrations.RemoveField(
            model_name='enrolmentfact',
            name='geography',
        ),
        migrations.AlterUniqueTogether(
            name='geographymaster',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='geographymaster',
            name='dashboard_g_state_c84c72_idx',
        ),
        migrations.DeleteModel(
            name='BiometricUpdateFact',
        ),
        migrations.DeleteModel(
            name='DemographicFact',
        ),
        migrations.DeleteModel(
            name='EnrolmentFact',
        ),
        migrations.DeleteModel(
            name='GeographyMaster',
        ),
    ]
